/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs471projecttwo;

import java.io.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
/**
 *
 * @author Caroline Chey
 */
public class VFS_GUI extends javax.swing.JFrame {
    
   
    public ComputerOS mComp = new ComputerOS();
    String mBefore = ""; //"before" view of actual file system
    String mCurrent = "";
   
    /**
     * Creates new form VFS_GUI
     */
    public VFS_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaUserView = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaPrint = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        butClear = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaFS = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAreaFSbefore = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        butInitialize = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtFieldFilepath = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFieldFiledata = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        butAddFile = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        butDeleteFile = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        butPrintFile = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        radD = new javax.swing.JRadioButton();
        radI = new javax.swing.JRadioButton();
        radV = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        butExit = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Virtual File System");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));

        txtAreaUserView.setEditable(false);
        txtAreaUserView.setColumns(20);
        txtAreaUserView.setRows(5);
        jScrollPane1.setViewportView(txtAreaUserView);

        txtAreaPrint.setEditable(false);
        txtAreaPrint.setColumns(20);
        txtAreaPrint.setRows(5);
        jScrollPane2.setViewportView(txtAreaPrint);

        jLabel7.setText("----- Print File here (one line unique data)");

        butClear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        butClear.setText("Clear");
        butClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butClearActionPerformed(evt);
            }
        });

        txtAreaFS.setEditable(false);
        txtAreaFS.setColumns(20);
        txtAreaFS.setRows(5);
        jScrollPane3.setViewportView(txtAreaFS);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("User View  ( filepath ) ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel11.setText("Actual File System Structure ( filetype  filepath  one-line data )");

        txtAreaFSbefore.setColumns(20);
        txtAreaFSbefore.setRows(5);
        jScrollPane4.setViewportView(txtAreaFSbefore);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel14.setText("Actual File System Structure___Before");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(49, 49, 49))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(butClear, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jScrollPane3, jScrollPane4});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(butClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane1, jScrollPane3, jScrollPane4});

        jLabel7.getAccessibleContext().setAccessibleName("");

        butInitialize.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        butInitialize.setForeground(new java.awt.Color(0, 102, 0));
        butInitialize.setText("Initialize System");
        butInitialize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butInitializeActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 102, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Filepath : ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("One line data : ");

        jLabel2.setText("To add a file, type in a valid file path and one line of unique data ...");
        jLabel2.setToolTipText("");

        butAddFile.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        butAddFile.setText("Add File");
        butAddFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAddFileActionPerformed(evt);
            }
        });

        jLabel6.setText("To delete a file, type in a valid file path ...");

        butDeleteFile.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        butDeleteFile.setForeground(new java.awt.Color(255, 102, 0));
        butDeleteFile.setText("Delete File");
        butDeleteFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDeleteFileActionPerformed(evt);
            }
        });

        jLabel8.setText("To print a file, type in a valid file path ...");

        butPrintFile.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        butPrintFile.setText("Print File");
        butPrintFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butPrintFileActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("File type : ");

        buttonGroup1.add(radD);
        radD.setText("d (d-node)");

        buttonGroup1.add(radI);
        radI.setText("i (i-node)");

        buttonGroup1.add(radV);
        radV.setText("v (v-node)");

        jLabel13.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel13.setText(" *** file path must start with \"/\" ... AND filename, filepath, data CANNOT contain space (\" \")");
        jLabel13.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(butAddFile, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(butPrintFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(94, 94, 94)
                        .addComponent(butDeleteFile, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFieldFilepath)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(radD)
                                .addGap(18, 18, 18)
                                .addComponent(radI)
                                .addGap(18, 18, 18)
                                .addComponent(radV)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldFiledata))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(radD)
                    .addComponent(radI)
                    .addComponent(radV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3)
                    .addComponent(txtFieldFilepath, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtFieldFiledata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butPrintFile)
                    .addComponent(butAddFile)
                    .addComponent(butDeleteFile))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        butExit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        butExit.setText("Exit Program");
        butExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butExitActionPerformed(evt);
            }
        });

        jLabel12.setText("<--- Click to start");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(butInitialize, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(butExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(butInitialize, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(butExit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Fall2015 CS471 Project Two by Caroline Chey");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butClearActionPerformed
        // clears text area for printing one line file data
        txtAreaPrint.setText("");
        txtFieldFilepath.setText("");
        txtFieldFiledata.setText("");
        
        txtAreaFSbefore.setText("");
    }//GEN-LAST:event_butClearActionPerformed

    private void butExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butExitActionPerformed
        // exit program
        System.exit(0);
    }//GEN-LAST:event_butExitActionPerformed

    private void butInitializeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butInitializeActionPerformed
        // Load from driveA.txt, driveB.txt, driveC.txt 
        
        
        try {
                mComp.load("driveA");//build mFA from "driveA.txt"
                mComp.load("driveB");
                mComp.load("driveC");

                //updateGUI();
                

        } catch (FileNotFoundException ef) {
        } catch (IOException ei) {
        } catch (NullPointerException en) {
        } catch (Exception ex) {
            Logger.getLogger(VFS_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        updateGUI();
        
        
        //updateGUI(A,B,C);
        
        
        
    }//GEN-LAST:event_butInitializeActionPerformed

    private void butPrintFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butPrintFileActionPerformed
        // prints file's one-line data
        
        if(((txtFieldFilepath.getText()).trim()).equals("")) //if no file name is entered
        {
            JOptionPane.showMessageDialog(null, "No File path entered!", "CANNOT ADD FILE", JOptionPane.WARNING_MESSAGE);
            updateGUI();
            return;
        }
            
        String printFilePath = txtFieldFilepath.getText().trim();
 
        File printFile = mComp.findFile( printFilePath ).file; 
        
        
        if( printFile == null )
        {
            JOptionPane.showMessageDialog(null, "File not found!", "CANNOT PRINT FILE", JOptionPane.WARNING_MESSAGE);
            updateGUI();
            return;
        }
        
        else if(printFile.getType() == 'i')
        {
            txtAreaPrint.setText( ((Inode)printFile).mData );
            return;
        }
        else if(printFile.getType() == 'v')
        {
            txtAreaPrint.setText( "v-node; " + ((Vnode)printFile).mFileSystemName );
            return;
        }
        else if(printFile.getType() == 'd')
        {
            String printD = "d-node; contains the following\n";
            for(int p=0; p<5; ++p)
            {
                printD += ((Dnode)printFile).mEntries[p].filename + "   ";
            }
            txtAreaPrint.setText( printD );
            return;
        }
        
            JOptionPane.showMessageDialog(null, "Could not print " + printFilePath , "CANNOT PRINT FILE", JOptionPane.WARNING_MESSAGE);
            updateGUI();
            return;
            
    
    }//GEN-LAST:event_butPrintFileActionPerformed

    
    private void butAddFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAddFileActionPerformed

        //if invalid user entry
        if(((txtFieldFilepath.getText()).trim()).equals("")) //if no file name is entered
        { 
            JOptionPane.showMessageDialog(null, "No File path entered!", "CANNOT ADD FILE", JOptionPane.WARNING_MESSAGE);
            updateGUI();
            return;
        }
        
        String addFilePath = txtFieldFilepath.getText();
        String addFileData = txtFieldFiledata.getText().trim();
        char addFileType = 'x'; 
        if(radD.isSelected())           addFileType = 'd';
        else if(radI.isSelected())      addFileType = 'i';
        else if(radV.isSelected())      addFileType = 'v';

        if(((txtFieldFiledata.getText()).trim()).equals("") && addFileType=='i') //if no data entered
        { 
            JOptionPane.showMessageDialog(null, "i-node must contain One line!", "CANNOT ADD FILE", JOptionPane.WARNING_MESSAGE);
            updateGUI();
            return;   
        }

        String[] userpath = addFilePath.split("/",-1);
        String[] addToDir = new String[userpath.length-1]; //figuring out which directory to add to
        String addFilePath_Dir = "";
        for(int w=0; w<addToDir.length; ++w)
        {
            addToDir[w] = userpath[w];
            addFilePath_Dir += addToDir[w];
            if(w!=addToDir.length-1)
                addFilePath_Dir+="/";
        }
        

        Dnode currentDir = new Dnode();
        Dnode addToD = (Dnode)(mComp.findFile( addFilePath_Dir ).file);
        String newFName = userpath[userpath.length-1]; //name of file to be
        
        if(addToD == null)
        {
            System.err.println("\ndirectory not found");
            JOptionPane.showMessageDialog(null, "directory not found!", "CANNOT ADD FILE", JOptionPane.WARNING_MESSAGE);
            updateGUI();
            return;
        }
        else if (addToD.insertEntry( addFileType, newFName, addFileData ))
        {
            updateGUI();
            JOptionPane.showMessageDialog(null, addFilePath + "\nhas been added", "FILE ADDED", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else if( !addToD.insertEntry( addFileType, newFName, addFileData ) )
        {
            System.err.println("\ncannot add file " + addFileType + " ,newFName =" + newFName);
            JOptionPane.showMessageDialog(null, "cannot add  " + addFilePath + "\ndirectory full OR invalid file", "CANNOT ADD FILE", JOptionPane.WARNING_MESSAGE);
            updateGUI();
            return;
        }
    }//GEN-LAST:event_butAddFileActionPerformed

    
    
    private void butDeleteFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDeleteFileActionPerformed
        //locate and delete filename supplied by user
        String delFilePath = txtFieldFilepath.getText().trim();
        
        //if invalid user entry
        if(((txtFieldFilepath.getText()).trim()).equals("")) //if no file name is entered
        {
            JOptionPane.showMessageDialog(null, "No File path entered!", "CANNOT DELETE FILE", JOptionPane.WARNING_MESSAGE);
            updateGUI();
            return;
        }
        
        File delFile = mComp.findFile( delFilePath ).file; 
        
        
        if( delFile == null )
        {
            JOptionPane.showMessageDialog(null, "File not found!", "CANNOT DELETE FILE", JOptionPane.WARNING_MESSAGE);
            updateGUI();
            return;
        }
        else
        {
            Dnode delFrom = mComp.findFile(delFilePath).dir;
            char delType = mComp.findFile(delFilePath).file.getType();
            String delFName = mComp.findFile(delFilePath).filename;
            
            if( delFile.canDelete() )
            {
                    try {
                    delFrom.deleteFile( delFName ); //deleting file
                    updateGUI();
                    JOptionPane.showMessageDialog(null, delFilePath + "\nhas been deleted", "FILE DELETED", JOptionPane.WARNING_MESSAGE);
                    
                } catch (Exception ex) {
                    Logger.getLogger(VFS_GUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, delFilePath + " could not be deleted!", "CANNOT DELETE FILE", JOptionPane.WARNING_MESSAGE);
                updateGUI();
                return;
            }
        }

    }//GEN-LAST:event_butDeleteFileActionPerformed
    
    
   //function to locate a FileSystem
    public Dnode lookupFS(String FSname)
    {
        Dnode res = mComp.lookupDrive(FSname);
        
        if(res != null) return res;

        return null; //if nothing found
    }

   
    
    //update GUI 
    public void updateGUI()
    {
        try {
            txtAreaPrint.setText("");
            txtFieldFilepath.setText("");
            txtFieldFiledata.setText("");
            txtAreaFS.setText("");
            
            txtAreaFSbefore.setText( mBefore );
            txtAreaUserView.setText( mComp.printFS() );
            mCurrent = mComp.printFSForActual();
            txtAreaFS.setText( mCurrent );
            mBefore = mCurrent;
            
            
            
        } catch (NullPointerException en2){ 
        }
    }
    
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VFS_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VFS_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VFS_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VFS_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VFS_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAddFile;
    private javax.swing.JButton butClear;
    private javax.swing.JButton butDeleteFile;
    private javax.swing.JButton butExit;
    private javax.swing.JButton butInitialize;
    private javax.swing.JButton butPrintFile;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JRadioButton radD;
    private javax.swing.JRadioButton radI;
    private javax.swing.JRadioButton radV;
    private javax.swing.JTextArea txtAreaFS;
    private javax.swing.JTextArea txtAreaFSbefore;
    private javax.swing.JTextArea txtAreaPrint;
    private javax.swing.JTextArea txtAreaUserView;
    private javax.swing.JTextField txtFieldFiledata;
    private javax.swing.JTextField txtFieldFilepath;
    // End of variables declaration//GEN-END:variables

}